[project]
name = "canvas-accessibility-helper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.2.0",
    "pillow>=12.1.0",
    "pdf2image>=1.17.0",
    "python-docx>=1.1.2",
]
